### ISSUE TITLE
How to send transaction at "0" priority fees ?

### ISSUE THREAD

**Issue by Kokiiez** [Parms-Crypto/ORE-LEVEL-ONE#2]
let cu_limit_ix = ComputeBudgetInstruction::set_compute_unit_limit(
                            0 as u32,
                        );
                        let cu_price_ix =
                            ComputeBudgetInstruction::set_compute_unit_price(0); 

?

**Comment by Parms-Crypto** [comment]
.\ore.exe --rpc "your rpc" --keypair "your path" --priority-fee 0 mine --threads 1

**Comment by Kokiiez** [comment]
Oh ok, it's not really 0

**Comment by Parms-Crypto** [comment]
Priority fee =/= base fee

Base fee on solana is 0.000005 minimum for any transaction on the network. You can't achieve lower. 

Priority fee is in addition to base fee so in this case you are paying 0 more than required by the network. 

$ORE is trying to get people to pay 5-10 million on top of minimum base fee which is absolute waste. Therefor you should always pay 0 when mining.
