### ISSUE TITLE
Unfortunately it doesn't work

### ISSUE THREAD

**Issue by Kokiiez** [Parms-Crypto/ORE-LEVEL-ONE#4]
14 minutes to find the hash now with the cpu :(

Against 20 seconds before

**Comment by Parms-Crypto** [comment]
He changed the mutable code on chain this time. My mistake for dropping before he did his standard github routine. Lesson learned and I'll drop code after he does so he can't instantly counter and screw small miners.

This should open everyone's eyes to the level of centralization and manipulation taking place. 

He has proven that he will do whatever to the code on chain to give insiders advantage and profit off small miners and mining culture.
